# Generated by Django 5.2.4 on 2025-07-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('creative', 'Creative'), ('field_agent', 'Field Agent'), ('admin', 'Admin'), ('heva_team', 'HEVA Team')], default='creative', max_length=20),
        ),
    ]
