# Generated by Django 5.2.4 on 2025-07-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('elevated', 'Elevated'), ('admin', 'Administrator'), ('super_admin', 'Super Administrator')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='creative_skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.CharField(choices=[('0-1', '0-1 years'), ('2-5', '2-5 years'), ('6-10', '6-10 years'), ('10+', '10+ years')], default='0-1', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_medium',
            field=models.CharField(choices=[('digital', 'Digital'), ('traditional', 'Traditional'), ('mixed', 'Mixed Media'), ('performance', 'Performance')], default='digital', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('system_admin', 'System Administrator'), ('data_admin', 'Data Administrator'), ('user_admin', 'User Administrator'), ('content_admin', 'Content Administrator'), ('supervisor', 'Supervisor')], max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='security_clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='specializations',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
