# Generated by Django 5.2.4 on 2025-07-30 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InclusionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_users', models.IntegerField(default=0)),
                ('marginalized_users', models.IntegerField(default=0)),
                ('refugee_users', models.IntegerField(default=0)),
                ('pwd_users', models.IntegerField(default=0)),
                ('lgbtqi_users', models.IntegerField(default=0)),
                ('creative_users', models.IntegerField(default=0)),
                ('avg_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funding_requests', models.IntegerField(default=0)),
                ('total_stories', models.IntegerField(default=0)),
                ('approved_stories', models.IntegerField(default=0)),
                ('urgent_stories', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.CharField(default='pending', max_length=20)),
                ('risk_level', models.CharField(default='pending', max_length=20)),
                ('inclusion_score', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('financial_consistency', models.FloatField(default=0.0)),
                ('story_engagement', models.FloatField(default=0.0)),
                ('device_adaptation', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
