import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('preferredLanguage') || 'en';
  });

  useEffect(() => {
    if (currentLanguage === 'ar') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
    localStorage.setItem('preferredLanguage', currentLanguage);
  }, [currentLanguage]);

  const translations = {
    en: {
      // Basic Navigation
      welcome: 'Welcome to HEVA Inclusion',
      welcomeToHEVA: 'Welcome to HEVA Inclusion',
      inclusivePlatform: 'An inclusive platform empowering creative communities across Africa',
      empoweringCreatives: 'Empowering Creative Communities',
      selectUserType: 'Select Your User Type',
      iAmCreative: 'I am a Creative',
      iAmFieldAgent: 'I am a Field Agent',
      hevaTeam: 'HEVA Team',
      selectLanguage: 'Select Language',
      helpInstructions: 'Help & Instructions',
      help: 'Help',
      back: 'Back',
      close: 'Close',
      understand: 'I Understand',

      // User Descriptions
      creativeDescription: 'Artists, musicians, designers, and creative professionals seeking support and opportunities',
      agentDescription: 'NGO officers and community field agents managing creative programs',
      hevaDescription: 'HEVA team members and administrators overseeing platform operations',

      // Additional Options
      additionalOptions: 'Additional Options',
      securityInfo: 'Security Information',
      privacyPolicy: 'Privacy Policy',

      // Accessibility Features
      accessibilityFeatures: 'Accessibility Features',
      mobileOptimized: 'Mobile Optimized',
      desktopCompatible: 'Desktop Compatible',
      ussdSupport: 'USSD Support',
      voiceAssistance: 'Voice Assistance',
      accessible: 'Accessible',
      multilingual: 'Multilingual',
      offlineMode: 'Offline Mode',
      secure: 'Secure',
      adminPanel: 'Admin Panel',
      analytics: 'Analytics',

      // Safety & Security
      securePlatform: 'Secure Platform - Your data is protected',
      secureSession: 'Secure Session',
      insecureSession: 'Insecure Session',
      minutesLeft: 'minutes left',
      emergencyExit: 'Emergency Exit',
      sessionExpired: 'Session expired for security',
      privacyAccepted: 'Privacy policy accepted',
      privacyRequired: 'Privacy policy acceptance required',

      // Accessibility Controls
      accessibility: 'Accessibility',
      accessibilityMode: 'Accessibility Mode',
      highContrast: 'High Contrast',
      reducedMotion: 'Reduced Motion',
      voiceAssistant: 'Voice Assistant',
      audio: 'Audio',
      audioInstructions: 'Audio Instructions',
      smallFont: 'Small Font',
      mediumFont: 'Medium Font',
      largeFont: 'Large Font',
      fontSizeChanged: 'Font size changed',
      enabled: ' enabled',
      disabled: ' disabled',
      audioNotSupported: 'Audio not supported in this browser',

      // Privacy Notice
      privacyNotice: 'Privacy & Security Notice',
      dataProtection: 'Data Protection',
      dataCollection: 'We collect only necessary information to provide services',
      dataUsage: 'Your data is used solely for platform functionality',
      dataSecurity: 'All data is encrypted and securely stored',
      dataRights: 'You have full control over your personal information',
      safetyFeatures: 'Safety Features',
      autoLogout: 'Automatic logout after inactivity',
      dataEncryption: 'End-to-end data encryption',
      acceptAndContinue: 'Accept & Continue',
      decline: 'Decline',

      // Security Features
      securityFeatures: 'Security Features',
      dataEncryptionDesc: 'All your data is encrypted using industry-standard protocols',
      secureAuthentication: 'Secure Authentication',
      secureAuthenticationDesc: 'Multi-factor authentication and secure login processes',
      autoLogoutDesc: 'Automatic logout after 30 minutes of inactivity for your security',
      emergencyExitDesc: 'Quick exit button to immediately clear all data and redirect to safe page',

      // Keyboard Shortcuts
      keyboardShortcuts: 'Keyboard Shortcuts',
      alt1Creative: 'Alt + 1: Select Creative',
      alt2Agent: 'Alt + 2: Select Field Agent',
      alt3HEVA: 'Alt + 3: Select HEVA Team',
      altHHelp: 'Alt + H: Help',
      altLLanguage: 'Alt + L: Language',
      escapeExit: 'Escape: Emergency Exit',

      // Enhanced Onboarding - Marginalized Groups
      onboardingStep1Title: 'Basic Information',
      onboardingStep1Desc: 'Tell us about yourself',
      onboardingStep2Title: 'Identity & Community',
      onboardingStep2Desc: 'Help us understand your background and needs',
      onboardingStep3Title: 'Access & Technology',
      onboardingStep3Desc: 'Tell us about your device and access needs',
      onboardingStep4Title: 'Trust & References',
      onboardingStep4Desc: 'Build trust through community connections',
      onboardingStep5Title: 'Creative Profile',
      onboardingStep5Desc: 'Share your creative work and experience',
      onboardingStep6Title: 'Voice Introduction',
      onboardingStep6Desc: 'Record a brief voice introduction (optional)',
      onboardingStep7Title: 'Review & Consent',
      onboardingStep7Desc: 'Review your information and provide consent',

      // Inclusive Identity Fields
      labelGender: 'Gender Identity',
      selectGender: 'Select your gender',
      genderMale: 'Male',
      genderFemale: 'Female',
      genderNonBinary: 'Non-binary',
      genderOther: 'Other',
      genderPreferNotToSay: 'Prefer not to say',
      specifyGender: 'Please specify your gender',
      
      labelDisability: 'Do you have a disability?',
      selectDisability: 'Select disability status',
      disabilityYes: 'Yes',
      disabilityNo: 'No',
      disabilityPreferNotToSay: 'Prefer not to say',
      selectDisabilityType: 'Select type of disability',
      disabilityVisual: 'Visual impairment',
      disabilityHearing: 'Hearing impairment',
      disabilityMobility: 'Mobility impairment',
      disabilityCognitive: 'Cognitive impairment',
      disabilitySpeech: 'Speech impairment',
      disabilityOther: 'Other',
      specifyDisability: 'Please specify your disability',

      // Marginalized Groups
      labelMarginalizedGroups: 'Which of these describe you?',
      marginalizedGroupsHelp: 'Select all that apply. This helps us provide better support.',
      groupRefugee: 'Refugee',
      groupPWD: 'Person with Disability',
      groupLGBTQI: 'LGBTQI+',
      groupCreative: 'Creative Professional',
      groupLowIncome: 'Low Income',
      groupLowLiteracy: 'Low Literacy',
      groupRural: 'Rural Community',
      groupYouth: 'Youth (18-25)',
      groupElderly: 'Elderly (65+)',
      groupOther: 'Other',
      specifyOtherGroup: 'Please specify',
      noneSelected: 'None selected',

      // Device Access & Technology
      labelPrimaryDevice: 'What device do you use most?',
      deviceSmartphone: 'Smartphone',
      deviceFeaturePhone: 'Feature phone (basic phone)',
      deviceShared: 'Shared device',
      deviceComputer: 'Computer/laptop',
      deviceNone: 'No device',
      
      labelInternetAccess: 'How often do you have internet access?',
      selectInternetAccess: 'Select internet access',
      internetAlways: 'Always available',
      internetSometimes: 'Sometimes available',
      internetRarely: 'Rarely available',
      internetNever: 'Never available',
      
      labelLiteracyLevel: 'What is your literacy level?',
      selectLiteracyLevel: 'Select literacy level',
      literacyHigh: 'High (can read and write well)',
      literacyMedium: 'Medium (basic reading and writing)',
      literacyLow: 'Low (limited reading and writing)',
      literacyNone: 'Cannot read or write',
      
      labelPreferredFormat: 'How would you prefer to receive information?',
      formatText: 'Text',
      formatAudio: 'Audio',
      formatVideo: 'Video',
      formatIcons: 'Icons and pictures',

      // Trust & Social Proof
      trustBasedOnboarding: 'Trust-Based Onboarding',
      trustBasedOnboardingDesc: 'We believe in building trust through community connections. You can provide a reference from someone who knows you.',
      hasReference: 'I have a reference or community contact',
      labelReferenceName: 'Reference Name',
      placeholderReferenceName: 'Enter reference name',
      labelReferencePhone: 'Reference Phone',
      placeholderReferencePhone: 'Enter reference phone number',
      labelReferenceRelationship: 'Relationship to Reference',
      selectReferenceRelationship: 'Select relationship',
      referenceCommunityLeader: 'Community Leader',
      referencePeer: 'Peer/Friend',
      referenceMentor: 'Mentor',
      referenceFamily: 'Family Member',
      referenceOther: 'Other',
      
      privacyOptions: 'Privacy Options',
      enablePrivacyMode: 'Enable privacy mode',
      privacyModeHelp: 'Privacy mode hides sensitive information and provides additional security.',

      // Consent
      consentTitle: 'Consent & Data Protection',
      consentDataCollection: 'I consent to HEVA collecting and processing my data for support services',
      consentContact: 'I agree to be contacted about support opportunities',

      // Enhanced Creative Fields
      creativeFieldVisualArts: 'Visual Arts',
      creativeFieldMusic: 'Music',
      creativeFieldDance: 'Dance',
      creativeFieldTheater: 'Theater',
      creativeFieldFilmVideo: 'Film & Video',
      creativeFieldPhotography: 'Photography',
      creativeFieldCrafts: 'Crafts',
      creativeFieldDigitalArts: 'Digital Arts',
      creativeFieldLiterature: 'Literature',
      creativeFieldFashionDesign: 'Fashion Design',
      creativeFieldOther: 'Other',

      // Experience Levels
      experienceBeginner: 'Beginner',
      experienceIntermediate: 'Intermediate',
      experienceAdvanced: 'Advanced',
      experienceExpert: 'Expert',

      // Form Labels
      labelFullName: 'Full Name',
      labelEmail: 'Email Address',
      labelPhone: 'Phone Number',
      labelLocation: 'Location',
      labelCreativeField: 'Creative Field',
      labelExperience: 'Experience Level',
      labelBio: 'Bio/Description',
      labelProfileImage: 'Profile Image',

      // Placeholders
      placeholderFullName: 'Enter your full name',
      placeholderEmail: 'Enter your email address',
      placeholderPhone: 'Enter your phone number',
      placeholderLocation: 'Enter your location',
      placeholderCreativeField: 'Select your creative field',
      placeholderExperience: 'Select your experience level',
      placeholderBio: 'Tell us about yourself and your creative work',

      // Voice Recording
      startRecording: 'Start Recording',
      reRecord: 'Re-record',
      voiceRecorded: 'Voice introduction recorded',
      voiceRecordedSuccess: 'Voice introduction recorded successfully!',
      recordingHelp: 'Record a brief introduction about yourself and your creative work',
      microphoneAccessError: 'Could not access microphone',

      // File Upload
      chooseImage: 'Choose Image',
      uploaded: 'Uploaded',
      notUploaded: 'Not uploaded',
      recorded: 'Recorded',
      notRecorded: 'Not recorded',

      // Status
      status: 'Status',
      notProvided: 'Not provided',
      notSpecified: 'Not specified',

      // Navigation
      previous: 'Previous',
      next: 'Next',
      completeProfile: 'Complete Profile',
      profileCreatedSuccess: 'Profile created successfully!',
      profileCreationFailed: 'Failed to create profile',
      profileCreationError: 'An error occurred',

      // Financial Literacy Content
      financialLiteracyTitle: 'Financial Literacy',
      financialLiteracyDesc: 'Learn about managing money and building financial security',
      financialTip1: 'Save a small amount regularly, even if it\'s just a little',
      financialTip2: 'Keep track of your income and expenses',
      financialTip3: 'Build emergency savings for unexpected costs',
      financialTip4: 'Learn about different ways to save and invest',
      financialTip5: 'Understand your rights as a borrower',
      
      // Anti-Fraud & Transparency
      transparencyTitle: 'Transparency & Trust',
      transparencyDesc: 'We are committed to transparency and preventing fraud',
      fraudPrevention: 'Fraud Prevention',
      fraudPreventionDesc: 'We have systems in place to prevent fraud and ensure funds reach the right people',
      reportingFraud: 'Reporting Fraud',
      reportingFraudDesc: 'If you suspect fraud, please report it immediately',
      fundTracking: 'Fund Tracking',
      fundTrackingDesc: 'All funds are tracked and monitored to ensure proper use',

      // Cultural Adaptation
      culturalAdaptationTitle: 'Cultural Adaptation',
      culturalAdaptationDesc: 'Our platform adapts to your cultural context and needs',
      localExamples: 'Local Examples',
      localExamplesDesc: 'We use examples and content relevant to your community',
      culturalSensitivity: 'Cultural Sensitivity',
      culturalSensitivityDesc: 'We respect and honor your cultural traditions and practices',

      // Financial Literacy Additional Keys
      financialBasics: 'Financial Basics',
      savingsStrategies: 'Savings Strategies',
      creditAndLoans: 'Credit & Loans',
      businessFinance: 'Business Finance',
      financialTip1Desc: 'Start with small, regular savings. Even saving a small amount consistently builds good habits.',
      financialTip2Desc: 'Track your income and expenses to understand your spending patterns and identify areas to save.',
      financialTip3Desc: 'Build an emergency fund to cover unexpected expenses and avoid high-cost borrowing.',
      emergencyFund: 'Emergency Fund',
      emergencyFundDesc: 'Save 3-6 months of expenses for unexpected situations like medical emergencies or job loss.',
      goalSetting: 'Goal Setting',
      goalSettingDesc: 'Set specific, achievable financial goals with timelines to stay motivated and focused.',
      automaticSavings: 'Automatic Savings',
      automaticSavingsDesc: 'Set up automatic transfers to make saving effortless and consistent.',
      creditRights: 'Your Rights as a Borrower',
      creditRightsDesc: 'Understand your rights when borrowing money and how to protect yourself from unfair practices.',
      loanTypes: 'Types of Loans',
      loanTypesDesc: 'Learn about different loan types, their costs, and when each might be appropriate.',
      avoidingDebt: 'Avoiding Debt Traps',
      avoidingDebtDesc: 'Recognize high-cost borrowing and predatory lending practices that can lead to debt cycles.',
      businessBudget: 'Business Budgeting',
      businessBudgetDesc: 'Create and maintain a budget for your creative business to track income and expenses.',
      pricingStrategy: 'Pricing Your Work',
      pricingStrategyDesc: 'Learn how to price your creative work fairly while covering costs and making a profit.',
      cashFlow: 'Managing Cash Flow',
      cashFlowDesc: 'Understand the timing of income and expenses to maintain healthy business finances.',
      groupSpecificTips: 'Tips for Specific Groups',
      groupSpecificTipsDesc: 'Financial advice tailored to different communities and circumstances.',
      refugeeFinancialTips: 'Financial Tips for Refugees',
      refugeeTip1: 'Start building credit history with small, manageable loans or credit cards',
      refugeeTip2: 'Connect with community organizations that provide financial education and support',
      refugeeTip3: 'Learn about banking options and services available in your new location',
      pwdFinancialTips: 'Financial Tips for Persons with Disabilities',
      pwdTip1: 'Research disability benefits and financial assistance programs available to you',
      pwdTip2: 'Consider disability-friendly banking options and accessible financial services',
      pwdTip3: 'Build a support network for financial decision-making and planning',
      lgbtqiFinancialTips: 'Financial Tips for LGBTQI+ Community',
      lgbtqiTip1: 'Understand your rights in financial services and seek inclusive providers',
      lgbtqiTip2: 'Consider legal protections for financial planning and estate planning',
      lgbtqiTip3: 'Connect with LGBTQI+-friendly financial advisors and community resources',
      creativeFinancialTips: 'Financial Tips for Creative Professionals',
      creativeTip1: 'Diversify income streams to reduce financial vulnerability',
      creativeTip2: 'Set aside money for taxes and irregular income periods',
      creativeTip3: 'Invest in your skills and equipment to increase earning potential',

      // Marginalized Group Support Keys
      marginalizedGroupSupportTitle: 'Marginalized Group Support',
      marginalizedGroupSupportDesc: 'Specialized support and resources for refugees, PWDs, LGBTQI+, and other marginalized communities',
      selectYourGroup: 'Select Your Group',
      allGroups: 'All Groups',
      overviewOfAllGroups: 'Overview of All Groups',
      learnMore: 'Learn More',
      keyChallenges: 'Key Challenges',
      ourSolutions: 'Our Solutions',
      availableResources: 'Available Resources',
      
      // Refugee Support
      refugeeSupport: 'Refugee Support',
      refugeeSupportDesc: 'Comprehensive support for refugees and displaced persons',
      refugeeChallenge1: 'Language barriers and limited access to financial services',
      refugeeChallenge2: 'Lack of documentation and credit history',
      refugeeChallenge3: 'Limited knowledge of local financial systems',
      refugeeSolution1: 'Multilingual support and simplified financial education',
      refugeeSolution2: 'Alternative identification and credit-building programs',
      refugeeSolution3: 'Community-based financial literacy training',
      refugeeResource1: 'Financial Education Materials',
      refugeeResource1Desc: 'Multilingual guides and videos on basic financial concepts',
      refugeeResource2: 'Community Support Network',
      refugeeResource2Desc: 'Connect with local organizations and peer support groups',
      refugeeResource3: 'Legal and Documentation Help',
      refugeeResource3Desc: 'Assistance with legal documents and banking access',
      
      // PWD Support
      pwdSupport: 'Persons with Disabilities Support',
      pwdSupportDesc: 'Accessible financial services and support for persons with disabilities',
      pwdChallenge1: 'Limited accessibility of financial services and platforms',
      pwdChallenge2: 'Discrimination in financial services and employment',
      pwdChallenge3: 'Additional costs for assistive technologies and healthcare',
      pwdSolution1: 'Fully accessible platform with assistive technology support',
      pwdSolution2: 'Anti-discrimination policies and inclusive financial products',
      pwdSolution3: 'Specialized financial planning for disability-related expenses',
      pwdResource1: 'Accessibility Features',
      pwdResource1Desc: 'Screen readers, voice navigation, and other assistive technologies',
      pwdResource2: 'Rights and Advocacy',
      pwdResource2Desc: 'Information about disability rights and financial protections',
      pwdResource3: 'Peer Support Network',
      pwdResource3Desc: 'Connect with other persons with disabilities for support',
      
      // LGBTQI+ Support
      lgbtqiSupport: 'LGBTQI+ Support',
      lgbtqiSupportDesc: 'Inclusive financial services and support for LGBTQI+ community',
      lgbtqiChallenge1: 'Discrimination in financial services and employment',
      lgbtqiChallenge2: 'Limited access to family-based financial products',
      lgbtqiChallenge3: 'Legal barriers to financial planning and inheritance',
      lgbtqiSolution1: 'Inclusive policies and anti-discrimination measures',
      lgbtqiSolution2: 'Specialized financial products for diverse family structures',
      lgbtqiSolution3: 'Legal support for financial planning and estate planning',
      lgbtqiResource1: 'Inclusive Financial Services',
      lgbtqiResource1Desc: 'Financial products and services designed for LGBTQI+ community',
      lgbtqiResource2: 'Legal Support Network',
      lgbtqiResource2Desc: 'Legal assistance for financial planning and rights protection',
      lgbtqiResource3: 'Community Organizations',
      lgbtqiResource3Desc: 'Connect with LGBTQI+ organizations and support groups',
      
      // Creative Support
      creativeSupport: 'Creative Professional Support',
      creativeSupportDesc: 'Specialized support for creative professionals and artists',
      creativeChallenge1: 'Irregular income and cash flow management',
      creativeChallenge2: 'Limited access to traditional financial services',
      creativeChallenge3: 'Difficulty in valuing and monetizing creative work',
      creativeSolution1: 'Flexible financial products for irregular income',
      creativeSolution2: 'Alternative credit assessment methods',
      creativeSolution3: 'Business development and monetization support',
      creativeResource1: 'Financial Planning Tools',
      creativeResource1Desc: 'Tools and calculators for irregular income management',
      creativeResource2: 'Business Development',
      creativeResource2Desc: 'Support for building sustainable creative businesses',
      creativeResource3: 'Networking and Collaboration',
      creativeResource3Desc: 'Connect with other creative professionals and mentors',
      
      // Accessibility Features
      accessibilityFeatures: 'Accessibility Features',
      accessibilityFeaturesDesc: 'Our platform is designed to be accessible to everyone',
      accessibilityFeature1: 'Universal Design',
      accessibilityFeature1Desc: 'Platform designed for users of all abilities and backgrounds',
      accessibilityFeature2: 'Multilingual Support',
      accessibilityFeature2Desc: 'Available in multiple languages with cultural adaptation',
      accessibilityFeature3: 'Mobile-First Design',
      accessibilityFeature3Desc: 'Optimized for low-end devices and limited internet access',
      accessibilityFeature4: 'Offline Capabilities',
      accessibilityFeature4Desc: 'Core features work without constant internet connection',
      
      // Inclusion Principles
      inclusionPrinciples: 'Inclusion Principles',
      inclusionPrinciplesDesc: 'Our commitment to creating an inclusive financial ecosystem',
      inclusionPrinciple1: 'Dignity and Respect',
      inclusionPrinciple1Desc: 'Every person deserves dignified access to financial services',
      inclusionPrinciple2: 'Safety and Privacy',
      inclusionPrinciple2Desc: 'Protecting user data and ensuring safe financial transactions',
      inclusionPrinciple3: 'Cultural Sensitivity',
      inclusionPrinciple3Desc: 'Respecting diverse cultural backgrounds and practices',
      inclusionPrinciple4: 'Community Building',
      inclusionPrinciple4Desc: 'Building supportive networks and peer communities',
      
      // Contact Support
      needHelp: 'Need Help?',
      contactSupportDesc: 'We\'re here to help. Contact us through any of these methods.',
      phoneSupport: 'Phone Support',
      phoneSupportDesc: 'Call our support line for immediate assistance',
      emailSupport: 'Email Support',
      emailSupportDesc: 'Send us an email and we\'ll respond within 24 hours',
      localSupport: 'Local Support',
      localSupportDesc: 'Find support organizations in your local community',
    },
    sw: {
      // Basic Navigation
      welcome: 'Karibu kwenye HEVA Inclusion',
      welcomeToHEVA: 'Karibu kwenye HEVA Inclusion',
      inclusivePlatform: 'Jukwaa la kujumuisha linaloimarisha jamii za ubunifu barani Afrika',
      empoweringCreatives: 'Kuimarisha Jamii za Ubunifu',
      selectUserType: 'Chagua Aina ya Mtumiaji',
      iAmCreative: 'Mimi ni Mwenye Ubunifu',
      iAmFieldAgent: 'Mimi ni Mwakilishi wa Shambani',
      hevaTeam: 'Timu ya HEVA',
      selectLanguage: 'Chagua Lugha',
      helpInstructions: 'Msaada na Maagizo',
      help: 'Msaada',
      back: 'Rudi Nyuma',
      close: 'Funga',
      understand: 'Naelewa',

      // User Descriptions
      creativeDescription: 'Wasanii, wanamuziki, wabunifu, na wataalamu wa ubunifu wanaotafuta msaada na fursa',
      agentDescription: 'Maafisa wa NGO na mawakilishi wa jamii wanaosimamia programu za ubunifu',
      hevaDescription: 'Wanachama wa timu ya HEVA na wasimamizi wanaosimamia shughuli za jukwaa',

      // Additional Options
      additionalOptions: 'Chaguo za Ziada',
      securityInfo: 'Maelezo ya Usalama',
      privacyPolicy: 'Sera ya Faragha',

      // Accessibility Features
      accessibilityFeatures: 'Vipengele vya Ufikivu',
      mobileOptimized: 'Iliyoboreshwa kwa Simu',
      desktopCompatible: 'Inapatana na Kompyuta',
      ussdSupport: 'Msaada wa USSD',
      voiceAssistance: 'Msaada wa Sauti',
      accessible: 'Inafikika',
      multilingual: 'Lugha Nyingi',
      offlineMode: 'Hali ya Nje ya Mtandao',
      secure: 'Salama',
      adminPanel: 'Jopo la Usimamizi',
      analytics: 'Uchambuzi',

      // Safety & Security
      securePlatform: 'Jukwaa Salama - Data yako imelindwa',
      secureSession: 'Kipindi Salama',
      insecureSession: 'Kipindi Kisicho Salama',
      minutesLeft: 'dakika zilizobaki',
      emergencyExit: 'Kutoka kwa Dharura',
      sessionExpired: 'Kipindi kimeisha kwa usalama',
      privacyAccepted: 'Sera ya faragha imekubaliwa',
      privacyRequired: 'Kukubali sera ya faragha kunahitajika',

      // Accessibility Controls
      accessibility: 'Ufikivu',
      accessibilityMode: 'Hali ya Ufikivu',
      highContrast: 'Tofauti ya Juu',
      reducedMotion: 'Mwendo Ulioepushwa',
      voiceAssistant: 'Msaidizi wa Sauti',
      audio: 'Sauti',
      audioInstructions: 'Maagizo ya Sauti',
      smallFont: 'Herufi Ndogo',
      mediumFont: 'Herufi ya Kati',
      largeFont: 'Herufi Kubwa',
      fontSizeChanged: 'Ukubwa wa herufi umebadilishwa',
      enabled: ' imewezeshwa',
      disabled: ' imezimwa',
      audioNotSupported: 'Sauti haitumiwi katika browser hii',

      // Privacy Notice
      privacyNotice: 'Ilani ya Faragha na Usalama',
      dataProtection: 'Ulinzi wa Data',
      dataCollection: 'Tunakusanya tu maelezo muhimu kutoa huduma',
      dataUsage: 'Data yako inatumika tu kwa utendaji wa jukwaa',
      dataSecurity: 'Data yote imesimbwa na kuhifadhiwa kwa usalama',
      dataRights: 'Una udhibiti kamili wa maelezo yako binafsi',
      safetyFeatures: 'Vipengele vya Usalama',
      autoLogout: 'Kutoka moja kwa moja baada ya kutokuwa na shughuli',
      dataEncryption: 'Ufungaji wa data kutoka mwanzo hadi mwisho',
      acceptAndContinue: 'Kubali na Endelea',
      decline: 'Kataa',

      // Security Features
      securityFeatures: 'Vipengele vya Usalama',
      dataEncryptionDesc: 'Data yako yote imesimbwa kwa kutumia itifaki za kiwango cha sekta',
      secureAuthentication: 'Uthibitishaji Salama',
      secureAuthenticationDesc: 'Uthibitishaji wa mambo mengi na michakato salama ya kuingia',
      autoLogoutDesc: 'Kutoka moja kwa moja baada ya dakika 30 za kutokuwa na shughuli kwa usalama wako',
      emergencyExitDesc: 'Kitufe cha kutoka haraka ili kufuta data yote mara moja na kuelekeza kwenye ukurasa salama',

      // Keyboard Shortcuts
      keyboardShortcuts: 'Njia za Haraka za Kibodi',
      alt1Creative: 'Alt + 1: Chagua Mwenye Ubunifu',
      alt2Agent: 'Alt + 2: Chagua Mwakilishi wa Shambani',
      alt3HEVA: 'Alt + 3: Chagua Timu ya HEVA',
      altHHelp: 'Alt + H: Msaada',
      altLLanguage: 'Alt + L: Lugha',
      escapeExit: 'Escape: Kutoka kwa Dharura',

      // Enhanced Onboarding - Marginalized Groups
      onboardingStep1Title: 'Maelezo ya Msingi',
      onboardingStep1Desc: 'Tuambie kuhusu wewe',
      onboardingStep2Title: 'Utambulisho na Jamii',
      onboardingStep2Desc: 'Tusaidie kuelewa asili yako na mahitaji',
      onboardingStep3Title: 'Ufikivu na Teknolojia',
      onboardingStep3Desc: 'Tuambie kuhusu kifaa chako na mahitaji ya ufikivu',
      onboardingStep4Title: 'Uaminifu na Marejeleo',
      onboardingStep4Desc: 'Jenga uaminifu kupitia uhusiano wa jamii',
      onboardingStep5Title: 'Wasifu wa Ubunifu',
      onboardingStep5Desc: 'Shiriki kazi yako ya ubunifu na uzoefu',
      onboardingStep6Title: 'Utangulizi wa Sauti',
      onboardingStep6Desc: 'Rekodi utangulizi mfupi wa sauti (hiari)',
      onboardingStep7Title: 'Mapitio na Idhini',
      onboardingStep7Desc: 'Pitia maelezo yako na toa idhini',

      // Inclusive Identity Fields
      labelGender: 'Utambulisho wa Jinsia',
      selectGender: 'Chagua jinsia yako',
      genderMale: 'Mwanaume',
      genderFemale: 'Mwanamke',
      genderNonBinary: 'Si wa kawaida',
      genderOther: 'Nyingine',
      genderPreferNotToSay: 'Sipendi kusema',
      specifyGender: 'Tafadhali eleza jinsia yako',
      
      labelDisability: 'Una ulemavu?',
      selectDisability: 'Chagua hali ya ulemavu',
      disabilityYes: 'Ndiyo',
      disabilityNo: 'Hapana',
      disabilityPreferNotToSay: 'Sipendi kusema',
      selectDisabilityType: 'Chagua aina ya ulemavu',
      disabilityVisual: 'Ulemavu wa kuona',
      disabilityHearing: 'Ulemavu wa kusikia',
      disabilityMobility: 'Ulemavu wa kusonga',
      disabilityCognitive: 'Ulemavu wa akili',
      disabilitySpeech: 'Ulemavu wa kuzungumza',
      disabilityOther: 'Nyingine',
      specifyDisability: 'Tafadhali eleza ulemavu wako',

      // Marginalized Groups
      labelMarginalizedGroups: 'Ni ipi kati ya hizi inakuelezea?',
      marginalizedGroupsHelp: 'Chagua zote zinazofaa. Hii inatusaidia kutoa msaada bora.',
      groupRefugee: 'Mkimbizi',
      groupPWD: 'Mtu aliye na Ulemavu',
      groupLGBTQI: 'LGBTQI+',
      groupCreative: 'Mtaalamu wa Ubunifu',
      groupLowIncome: 'Mapato ya Chini',
      groupLowLiteracy: 'Kusoma na Kuandika Kidogo',
      groupRural: 'Jamii ya Vijijini',
      groupYouth: 'Vijana (18-25)',
      groupElderly: 'Wazee (65+)',
      groupOther: 'Nyingine',
      specifyOtherGroup: 'Tafadhali eleza',
      noneSelected: 'Hakuna iliyochaguliwa',

      // Device Access & Technology
      labelPrimaryDevice: 'Ni kifaa gani unachotumia zaidi?',
      deviceSmartphone: 'Simu ya Smartphone',
      deviceFeaturePhone: 'Simu ya kawaida (simu rahisi)',
      deviceShared: 'Kifaa cha kushiriki',
      deviceComputer: 'Kompyuta/laptop',
      deviceNone: 'Hakuna kifaa',
      
      labelInternetAccess: 'Mara ngapi una ufikivu wa mtandao?',
      selectInternetAccess: 'Chagua ufikivu wa mtandao',
      internetAlways: 'Inapatikana kila wakati',
      internetSometimes: 'Inapatikana wakati mwingine',
      internetRarely: 'Inapatikana mara chache',
      internetNever: 'Haipatikani kamwe',
      
      labelLiteracyLevel: 'Je, kiwango chako cha kusoma na kuandika ni nini?',
      selectLiteracyLevel: 'Chagua kiwango cha kusoma na kuandika',
      literacyHigh: 'Juu (anaweza kusoma na kuandika vizuri)',
      literacyMedium: 'Wastani (kusoma na kuandika kwa msingi)',
      literacyLow: 'Chini (kusoma na kuandika kidogo)',
      literacyNone: 'Hawiwezi kusoma au kuandika',
      
      labelPreferredFormat: 'Ungependa kupokea maelezo kwa njia gani?',
      formatText: 'Maandishi',
      formatAudio: 'Sauti',
      formatVideo: 'Video',
      formatIcons: 'Alama na picha',

      // Trust & Social Proof
      trustBasedOnboarding: 'Kujisajili kwa Uaminifu',
      trustBasedOnboardingDesc: 'Tunaamini katika kujenga uaminifu kupitia uhusiano wa jamii. Unaweza kutoa mrejeleo kutoka kwa mtu anayekujua.',
      hasReference: 'Nina mrejeleo au mhusika wa jamii',
      labelReferenceName: 'Jina la Mrejeleo',
      placeholderReferenceName: 'Weka jina la mrejeleo',
      labelReferencePhone: 'Simu ya Mrejeleo',
      placeholderReferencePhone: 'Weka nambari ya simu ya mrejeleo',
      labelReferenceRelationship: 'Uhusiano na Mrejeleo',
      selectReferenceRelationship: 'Chagua uhusiano',
      referenceCommunityLeader: 'Kiongozi wa Jamii',
      referencePeer: 'Mwenzi/Rafiki',
      referenceMentor: 'Mshauri',
      referenceFamily: 'Mwanafamilia',
      referenceOther: 'Nyingine',
      
      privacyOptions: 'Chaguo za Faragha',
      enablePrivacyMode: 'Washa hali ya faragha',
      privacyModeHelp: 'Hali ya faragha huficha maelezo nyeti na inatoa usalama wa ziada.',

      // Consent
      consentTitle: 'Idhini na Ulinzi wa Data',
      consentDataCollection: 'Ninakubali HEVA ikusanye na kuchakata data yangu kwa huduma za msaada',
      consentContact: 'Ninakubali kuwasiliana nami kuhusu fursa za msaada',

      // Enhanced Creative Fields
      creativeFieldVisualArts: 'Sanaa za Kuona',
      creativeFieldMusic: 'Muziki',
      creativeFieldDance: 'Ngoma',
      creativeFieldTheater: 'Tamthilia',
      creativeFieldFilmVideo: 'Filamu na Video',
      creativeFieldPhotography: 'Upigaji Picha',
      creativeFieldCrafts: 'Ufundi',
      creativeFieldDigitalArts: 'Sanaa za Kidijitali',
      creativeFieldLiterature: 'Fasihi',
      creativeFieldFashionDesign: 'Muundo wa Mitindo',
      creativeFieldOther: 'Nyingine',

      // Experience Levels
      experienceBeginner: 'Mwanzo',
      experienceIntermediate: 'Wastani',
      experienceAdvanced: 'Juu',
      experienceExpert: 'Mtaalamu',

      // Form Labels
      labelFullName: 'Jina Kamili',
      labelEmail: 'Barua Pepe',
      labelPhone: 'Nambari ya Simu',
      labelLocation: 'Mahali',
      labelCreativeField: 'Shughuli ya Ubunifu',
      labelExperience: 'Kiwango cha Uzoefu',
      labelBio: 'Maelezo',
      labelProfileImage: 'Picha ya Wasifu',

      // Placeholders
      placeholderFullName: 'Weka jina lako kamili',
      placeholderEmail: 'Weka barua pepe yako',
      placeholderPhone: 'Weka nambari yako ya simu',
      placeholderLocation: 'Weka mahali pako',
      placeholderCreativeField: 'Chagua shughuli yako ya ubunifu',
      placeholderExperience: 'Chagua kiwango chako cha uzoefu',
      placeholderBio: 'Tuambie kuhusu wewe na kazi yako ya ubunifu',

      // Voice Recording
      startRecording: 'Anza Kurekodi',
      reRecord: 'Rekodi tena',
      voiceRecorded: 'Utangulizi wa sauti umerekodiwa',
      voiceRecordedSuccess: 'Utangulizi wa sauti umerekodiwa kwa mafanikio!',
      recordingHelp: 'Rekodi utangulizi mfupi kuhusu wewe na kazi yako ya ubunifu',
      microphoneAccessError: 'Haikuweza kufikia kipaza sauti',

      // File Upload
      chooseImage: 'Chagua Picha',
      uploaded: 'Imewekwa',
      notUploaded: 'Haijawekwa',
      recorded: 'Imerekodiwa',
      notRecorded: 'Haijarekodiwa',

      // Status
      status: 'Hali',
      notProvided: 'Haijatolewa',
      notSpecified: 'Haijatajwa',

      // Navigation
      previous: 'Iliyotangulia',
      next: 'Ifuatayo',
      completeProfile: 'Kamilisha Wasifu',
      profileCreatedSuccess: 'Wasifu umetengenezwa kwa mafanikio!',
      profileCreationFailed: 'Imeshindwa kutengeneza wasifu',
      profileCreationError: 'Hitilafu imetokea',

      // Financial Literacy Content
      financialLiteracyTitle: 'Elimu ya Fedha',
      financialLiteracyDesc: 'Jifunze kuhusu kusimamia pesa na kujenga usalama wa kifedha',
      financialTip1: 'Oka kiasi kidogo mara kwa mara, hata kama ni kidogo tu',
      financialTip2: 'Fuatilia mapato na gharama zako',
      financialTip3: 'Jenga akiba ya dharura kwa gharama zisizotarajiwa',
      financialTip4: 'Jifunze kuhusu njia mbalimbali za kuweka akiba na kuwekeza',
      financialTip5: 'Elewa haki zako kama mkopaji',
      
      // Anti-Fraud & Transparency
      transparencyTitle: 'Uwazi na Uaminifu',
      transparencyDesc: 'Tumejitolea kwa uwazi na kuzuia udanganyifu',
      fraudPrevention: 'Kuzuia Udanganyifu',
      fraudPreventionDesc: 'Tuna mifumo ya kuzuia udanganyifu na kuhakikisha fedha zinafikia watu sahihi',
      reportingFraud: 'Kuripoti Udanganyifu',
      reportingFraudDesc: 'Ikiwa unashuku udanganyifu, tafadhali uripoti mara moja',
      fundTracking: 'Kufuatilia Fedha',
      fundTrackingDesc: 'Fedha zote zinafuatiliwa na kufuatiliwa ili kuhakikisha matumizi sahihi',

      // Cultural Adaptation
      culturalAdaptationTitle: 'Marekebisho ya Kitamaduni',
      culturalAdaptationDesc: 'Jukwaa letu linarekebishwa kulingana na muktadha wako wa kitamaduni na mahitaji',
      localExamples: 'Mifano ya Kienyeji',
      localExamplesDesc: 'Tunatumia mifano na maudhui yanayohusiana na jamii yako',
      culturalSensitivity: 'Ustahimilivu wa Kitamaduni',
      culturalSensitivityDesc: 'Tunaheshimu na kuheshimu mila na desturi zako za kitamaduni',

      // Financial Literacy Additional Keys
      financialBasics: 'Misingi ya Fedha',
      savingsStrategies: 'Mbinu za Kuweka Akiba',
      creditAndLoans: 'Mikopo na Mabenki',
      businessFinance: 'Fedha za Biashara',
      financialTip1Desc: 'Anza na akiba ndogo, ya mara kwa mara. Hata kuweka akiba kiasi kidogo kwa mara kwa mara hujenga tabia nzuri.',
      financialTip2Desc: 'Fuatilia mapato na gharama zako ili kuelewa muundo wa matumizi yako na kutambua maeneo ya kuweka akiba.',
      financialTip3Desc: 'Jenga akiba ya dharura kufidia gharama zisizotarajiwa na kuepuka kukopa kwa gharama kubwa.',
      emergencyFund: 'Akiba ya Dharura',
      emergencyFundDesc: 'Weka akiba ya gharama za miezi 3-6 kwa hali zisizotarajiwa kama dharura za matibabu au kupoteza kazi.',
      goalSetting: 'Kuweka Malengo',
      goalSettingDesc: 'Weka malengo mahususi, yanayoweza kufikiwa ya kifedha na ratiba za muda ili kudumisha motisha na kujikita.',
      automaticSavings: 'Akiba ya Moja kwa Moja',
      automaticSavingsDesc: 'Weka uhamishaji wa moja kwa moja ili kuweka akiba kuwa rahisi na thabiti.',
      creditRights: 'Haki Zako kama Mkopaji',
      creditRightsDesc: 'Elewa haki zako wakati wa kukopa pesa na jinsi ya kujilinda kutoka kwa mazoea yasiyo ya haki.',
      loanTypes: 'Aina za Mikopo',
      loanTypesDesc: 'Jifunze kuhusu aina mbalimbali za mikopo, gharama zao, na wakati kila moja inaweza kuwa mwafaka.',
      avoidingDebt: 'Kuepuka Mitego ya Deni',
      avoidingDebtDesc: 'Tambua kukopa kwa gharama kubwa na mazoea ya ufadhili wa kudanganya yanayoweza kusababisha mizunguko ya deni.',
      businessBudget: 'Bajeti ya Biashara',
      businessBudgetDesc: 'Unda na udumishe bajeti kwa biashara yako ya ubunifu ili kufuatilia mapato na gharama.',
      pricingStrategy: 'Kuweka Bei ya Kazi Yako',
      pricingStrategyDesc: 'Jifunze jinsi ya kuweka bei ya kazi yako ya ubunifu kwa haki wakati wa kufidia gharama na kufanya faida.',
      cashFlow: 'Kusimamia Mwendo wa Fedha',
      cashFlowDesc: 'Elewa wakati wa mapato na gharama ili kudumisha fedha za biashara zenye afya.',
      groupSpecificTips: 'Vidokezo kwa Vikundi Maalum',
      groupSpecificTipsDesc: 'Ushauri wa kifedha uliotengenezwa kwa jamii na hali tofauti.',
      refugeeFinancialTips: 'Vidokezo vya Fedha kwa Wakimbizi',
      refugeeTip1: 'Anza kujenga historia ya mkopo na mikopo ndogo, inayoweza kusimamiwa au kadi za mkopo',
      refugeeTip2: 'Uhusiane na mashirika ya jamii yanayotoa elimu ya fedha na msaada',
      refugeeTip3: 'Jifunze kuhusu chaguo za benki na huduma zinazopatikana katika eneo lako jipya',
      pwdFinancialTips: 'Vidokezo vya Fedha kwa Watu wenye Ulemavu',
      pwdTip1: 'Chunguza faida za ulemavu na programu za msaada wa fedha zinazopatikana kwako',
      pwdTip2: 'Fikiria chaguo za benki zinazofaa ulemavu na huduma za fedha zinazofikika',
      pwdTip3: 'Jenga mtandao wa msaada kwa uamuzi wa fedha na kupanga',
      lgbtqiFinancialTips: 'Vidokezo vya Fedha kwa Jamii ya LGBTQI+',
      lgbtqiTip1: 'Elewa haki zako katika huduma za fedha na kutafuta watoa huduma wenye kujumuisha',
      lgbtqiTip2: 'Fikiria ulinzi wa kisheria kwa kupanga fedha na kupanga mali',
      lgbtqiTip3: 'Uhusiane na washauri wa fedha wenye kufaa LGBTQI+ na rasilimali za jamii',
      creativeFinancialTips: 'Vidokezo vya Fedha kwa Wataalamu wa Ubunifu',
      creativeTip1: 'Tofautisha vyanzo vya mapato ili kupunguza udhaifu wa kifedha',
      creativeTip2: 'Weka pesa kando kwa kodi na vipindi vya mapato yasiyo ya kawaida',
      creativeTip3: 'Wekeza katika ujuzi wako na vifaa ili kuongeza uwezo wa kupata mapato',
    },
    fr: {
      // Basic Navigation
      welcome: 'Bienvenue sur HEVA Inclusion',
      welcomeToHEVA: 'Bienvenue sur HEVA Inclusion',
      inclusivePlatform: 'Une plateforme inclusive qui autonomise les communautés créatives à travers l\'Afrique',
      empoweringCreatives: 'Autonomiser les Communautés Créatives',
      selectUserType: 'Sélectionnez Votre Type d\'Utilisateur',
      iAmCreative: 'Je suis un Créatif',
      iAmFieldAgent: 'Je suis un Agent de Terrain',
      hevaTeam: 'Équipe HEVA',
      selectLanguage: 'Sélectionner la Langue',
      helpInstructions: 'Aide et Instructions',
      help: 'Aide',
      back: 'Retour',
      close: 'Fermer',
      understand: 'Je Comprends',

      // User Descriptions
      creativeDescription: 'Artistes, musiciens, designers et professionnels créatifs recherchant soutien et opportunités',
      agentDescription: 'Officiers d\'ONG et agents de terrain communautaires gérant des programmes créatifs',
      hevaDescription: 'Membres de l\'équipe HEVA et administrateurs supervisant les opérations de la plateforme',

      // Additional Options
      additionalOptions: 'Options Supplémentaires',
      securityInfo: 'Informations de Sécurité',
      privacyPolicy: 'Politique de Confidentialité',

      // Accessibility Features
      accessibilityFeatures: 'Fonctionnalités d\'Accessibilité',
      mobileOptimized: 'Optimisé Mobile',
      desktopCompatible: 'Compatible Bureau',
      ussdSupport: 'Support USSD',
      voiceAssistance: 'Assistance Vocale',
      accessible: 'Accessible',
      multilingual: 'Multilingue',
      offlineMode: 'Mode Hors Ligne',
      secure: 'Sécurisé',
      adminPanel: 'Panneau d\'Administration',
      analytics: 'Analytiques',

      // Safety & Security
      securePlatform: 'Plateforme Sécurisée - Vos données sont protégées',
      secureSession: 'Session Sécurisée',
      insecureSession: 'Session Non Sécurisée',
      minutesLeft: 'minutes restantes',
      emergencyExit: 'Sortie d\'Urgence',
      sessionExpired: 'Session expirée pour la sécurité',
      privacyAccepted: 'Politique de confidentialité acceptée',
      privacyRequired: 'Acceptation de la politique de confidentialité requise',

      // Accessibility Controls
      accessibility: 'Accessibilité',
      accessibilityMode: 'Mode Accessibilité',
      highContrast: 'Contraste Élevé',
      reducedMotion: 'Mouvement Réduit',
      voiceAssistant: 'Assistant Vocal',
      audio: 'Audio',
      audioInstructions: 'Instructions Audio',
      smallFont: 'Petite Police',
      mediumFont: 'Police Moyenne',
      largeFont: 'Grande Police',
      fontSizeChanged: 'Taille de police modifiée',
      enabled: ' activé',
      disabled: ' désactivé',
      audioNotSupported: 'Audio non pris en charge dans ce navigateur',

      // Privacy Notice
      privacyNotice: 'Avis de Confidentialité et de Sécurité',
      dataProtection: 'Protection des Données',
      dataCollection: 'Nous collectons uniquement les informations nécessaires pour fournir des services',
      dataUsage: 'Vos données sont utilisées uniquement pour la fonctionnalité de la plateforme',
      dataSecurity: 'Toutes les données sont chiffrées et stockées en toute sécurité',
      dataRights: 'Vous avez un contrôle total sur vos informations personnelles',
      safetyFeatures: 'Fonctionnalités de Sécurité',
      autoLogout: 'Déconnexion automatique après inactivité',
      dataEncryption: 'Chiffrement des données de bout en bout',
      acceptAndContinue: 'Accepter et Continuer',
      decline: 'Refuser',

      // Security Features
      securityFeatures: 'Fonctionnalités de Sécurité',
      dataEncryptionDesc: 'Toutes vos données sont chiffrées à l\'aide de protocoles conformes aux normes de l\'industrie',
      secureAuthentication: 'Authentification Sécurisée',
      secureAuthenticationDesc: 'Authentification multi-facteurs et processus de connexion sécurisés',
      autoLogoutDesc: 'Déconnexion automatique après 30 minutes d\'inactivité pour votre sécurité',
      emergencyExitDesc: 'Bouton de sortie rapide pour effacer immédiatement toutes les données et rediriger vers une page sûre',

      // Keyboard Shortcuts
      keyboardShortcuts: 'Raccourcis Clavier',
      alt1Creative: 'Alt + 1: Sélectionner Créatif',
      alt2Agent: 'Alt + 2: Sélectionner Agent de Terrain',
      alt3HEVA: 'Alt + 3: Sélectionner Équipe HEVA',
      altHHelp: 'Alt + H: Aide',
      altLLanguage: 'Alt + L: Langue',
      escapeExit: 'Échap: Sortie d\'Urgence',

      // Enhanced Onboarding - Marginalized Groups
      onboardingStep1Title: 'Informations de Base',
      onboardingStep1Desc: 'Parlez-nous de vous',
      onboardingStep2Title: 'Identité et Communauté',
      onboardingStep2Desc: 'Aidez-nous à comprendre votre contexte et vos besoins',
      onboardingStep3Title: 'Accès et Technologie',
      onboardingStep3Desc: 'Parlez-nous de votre appareil et de vos besoins d\'accès',
      onboardingStep4Title: 'Confiance et Références',
      onboardingStep4Desc: 'Construire la confiance par les connexions communautaires',
      onboardingStep5Title: 'Profil Créatif',
      onboardingStep5Desc: 'Partagez votre travail créatif et votre expérience',
      onboardingStep6Title: 'Introduction Vocale',
      onboardingStep6Desc: 'Enregistrez une brève introduction vocale (optionnel)',
      onboardingStep7Title: 'Révision et Consentement',
      onboardingStep7Desc: 'Révisez vos informations et donnez votre consentement',

      // Inclusive Identity Fields
      labelGender: 'Identité de Genre',
      selectGender: 'Sélectionnez votre genre',
      genderMale: 'Homme',
      genderFemale: 'Femme',
      genderNonBinary: 'Non-binaire',
      genderOther: 'Autre',
      genderPreferNotToSay: 'Préfère ne pas dire',
      specifyGender: 'Veuillez préciser votre genre',
      
      labelDisability: 'Avez-vous un handicap?',
      selectDisability: 'Sélectionnez le statut de handicap',
      disabilityYes: 'Oui',
      disabilityNo: 'Non',
      disabilityPreferNotToSay: 'Préfère ne pas dire',
      selectDisabilityType: 'Sélectionnez le type de handicap',
      disabilityVisual: 'Handicap visuel',
      disabilityHearing: 'Handicap auditif',
      disabilityMobility: 'Handicap moteur',
      disabilityCognitive: 'Handicap cognitif',
      disabilitySpeech: 'Handicap de la parole',
      disabilityOther: 'Autre',
      specifyDisability: 'Veuillez préciser votre handicap',

      // Marginalized Groups
      labelMarginalizedGroups: 'Lequel de ces éléments vous décrit?',
      marginalizedGroupsHelp: 'Sélectionnez tous ceux qui s\'appliquent. Cela nous aide à fournir un meilleur soutien.',
      groupRefugee: 'Réfugié',
      groupPWD: 'Personne Handicapée',
      groupLGBTQI: 'LGBTQI+',
      groupCreative: 'Professionnel Créatif',
      groupLowIncome: 'Faible Revenu',
      groupLowLiteracy: 'Faible Alphabétisation',
      groupRural: 'Communauté Rurale',
      groupYouth: 'Jeune (18-25)',
      groupElderly: 'Personne Âgée (65+)',
      groupOther: 'Autre',
      specifyOtherGroup: 'Veuillez préciser',
      noneSelected: 'Aucun sélectionné',

      // Device Access & Technology
      labelPrimaryDevice: 'Quel appareil utilisez-vous le plus?',
      deviceSmartphone: 'Smartphone',
      deviceFeaturePhone: 'Téléphone basique',
      deviceShared: 'Appareil partagé',
      deviceComputer: 'Ordinateur/portable',
      deviceNone: 'Aucun appareil',
      
      labelInternetAccess: 'À quelle fréquence avez-vous accès à Internet?',
      selectInternetAccess: 'Sélectionnez l\'accès Internet',
      internetAlways: 'Toujours disponible',
      internetSometimes: 'Parfois disponible',
      internetRarely: 'Rarement disponible',
      internetNever: 'Jamais disponible',
      
      labelLiteracyLevel: 'Quel est votre niveau d\'alphabétisation?',
      selectLiteracyLevel: 'Sélectionnez le niveau d\'alphabétisation',
      literacyHigh: 'Élevé (peut bien lire et écrire)',
      literacyMedium: 'Moyen (lecture et écriture de base)',
      literacyLow: 'Faible (lecture et écriture limitées)',
      literacyNone: 'Ne peut pas lire ou écrire',
      
      labelPreferredFormat: 'Comment préférez-vous recevoir les informations?',
      formatText: 'Texte',
      formatAudio: 'Audio',
      formatVideo: 'Vidéo',
      formatIcons: 'Icônes et images',

      // Trust & Social Proof
      trustBasedOnboarding: 'Inscription Basée sur la Confiance',
      trustBasedOnboardingDesc: 'Nous croyons en la construction de la confiance par les connexions communautaires. Vous pouvez fournir une référence de quelqu\'un qui vous connaît.',
      hasReference: 'J\'ai une référence ou un contact communautaire',
      labelReferenceName: 'Nom de la Référence',
      placeholderReferenceName: 'Entrez le nom de la référence',
      labelReferencePhone: 'Téléphone de la Référence',
      placeholderReferencePhone: 'Entrez le numéro de téléphone de la référence',
      labelReferenceRelationship: 'Relation avec la Référence',
      selectReferenceRelationship: 'Sélectionnez la relation',
      referenceCommunityLeader: 'Leader Communautaire',
      referencePeer: 'Pair/Ami',
      referenceMentor: 'Mentor',
      referenceFamily: 'Membre de la Famille',
      referenceOther: 'Autre',
      
      privacyOptions: 'Options de Confidentialité',
      enablePrivacyMode: 'Activer le mode confidentialité',
      privacyModeHelp: 'Le mode confidentialité masque les informations sensibles et fournit une sécurité supplémentaire.',

      // Consent
      consentTitle: 'Consentement et Protection des Données',
      consentDataCollection: 'Je consens à ce qu\'HEVA collecte et traite mes données pour les services de soutien',
      consentContact: 'J\'accepte d\'être contacté concernant les opportunités de soutien',

      // Enhanced Creative Fields
      creativeFieldVisualArts: 'Arts Visuels',
      creativeFieldMusic: 'Musique',
      creativeFieldDance: 'Danse',
      creativeFieldTheater: 'Théâtre',
      creativeFieldFilmVideo: 'Cinéma et Vidéo',
      creativeFieldPhotography: 'Photographie',
      creativeFieldCrafts: 'Artisanat',
      creativeFieldDigitalArts: 'Arts Numériques',
      creativeFieldLiterature: 'Littérature',
      creativeFieldFashionDesign: 'Design de Mode',
      creativeFieldOther: 'Autre',

      // Experience Levels
      experienceBeginner: 'Débutant',
      experienceIntermediate: 'Intermédiaire',
      experienceAdvanced: 'Avancé',
      experienceExpert: 'Expert',

      // Form Labels
      labelFullName: 'Nom Complet',
      labelEmail: 'Adresse Email',
      labelPhone: 'Numéro de Téléphone',
      labelLocation: 'Localisation',
      labelCreativeField: 'Domaine Créatif',
      labelExperience: 'Niveau d\'Expérience',
      labelBio: 'Bio/Description',
      labelProfileImage: 'Image de Profil',

      // Placeholders
      placeholderFullName: 'Entrez votre nom complet',
      placeholderEmail: 'Entrez votre adresse email',
      placeholderPhone: 'Entrez votre numéro de téléphone',
      placeholderLocation: 'Entrez votre localisation',
      placeholderCreativeField: 'Sélectionnez votre domaine créatif',
      placeholderExperience: 'Sélectionnez votre niveau d\'expérience',
      placeholderBio: 'Parlez-nous de vous et de votre travail créatif',

      // Voice Recording
      startRecording: 'Commencer l\'Enregistrement',
      reRecord: 'Ré-enregistrer',
      voiceRecorded: 'Introduction vocale enregistrée',
      voiceRecordedSuccess: 'Introduction vocale enregistrée avec succès!',
      recordingHelp: 'Enregistrez une brève introduction sur vous et votre travail créatif',
      microphoneAccessError: 'Impossible d\'accéder au microphone',

      // File Upload
      chooseImage: 'Choisir une Image',
      uploaded: 'Téléchargé',
      notUploaded: 'Non téléchargé',
      recorded: 'Enregistré',
      notRecorded: 'Non enregistré',

      // Status
      status: 'Statut',
      notProvided: 'Non fourni',
      notSpecified: 'Non spécifié',

      // Navigation
      previous: 'Précédent',
      next: 'Suivant',
      completeProfile: 'Compléter le Profil',
      profileCreatedSuccess: 'Profil créé avec succès!',
      profileCreationFailed: 'Échec de la création du profil',
      profileCreationError: 'Une erreur s\'est produite',

      // Financial Literacy Content
      financialLiteracyTitle: 'Éducation Financière',
      financialLiteracyDesc: 'Apprenez à gérer l\'argent et à construire la sécurité financière',
      financialTip1: 'Épargnez régulièrement un petit montant, même si c\'est juste un peu',
      financialTip2: 'Suivez vos revenus et vos dépenses',
      financialTip3: 'Construisez une épargne d\'urgence pour les coûts imprévus',
      financialTip4: 'Apprenez sur différentes façons d\'épargner et d\'investir',
      financialTip5: 'Comprenez vos droits en tant qu\'emprunteur',
      
      // Anti-Fraud & Transparency
      transparencyTitle: 'Transparence et Confiance',
      transparencyDesc: 'Nous nous engageons à la transparence et à la prévention de la fraude',
      fraudPrevention: 'Prévention de la Fraude',
      fraudPreventionDesc: 'Nous avons des systèmes en place pour prévenir la fraude et assurer que les fonds atteignent les bonnes personnes',
      reportingFraud: 'Signaler la Fraude',
      reportingFraudDesc: 'Si vous soupçonnez une fraude, veuillez la signaler immédiatement',
      fundTracking: 'Suivi des Fonds',
      fundTrackingDesc: 'Tous les fonds sont suivis et surveillés pour assurer une utilisation appropriée',

      // Cultural Adaptation
      culturalAdaptationTitle: 'Adaptation Culturelle',
      culturalAdaptationDesc: 'Notre plateforme s\'adapte à votre contexte culturel et à vos besoins',
      localExamples: 'Exemples Locaux',
      localExamplesDesc: 'Nous utilisons des exemples et du contenu pertinents pour votre communauté',
      culturalSensitivity: 'Sensibilité Culturelle',
      culturalSensitivityDesc: 'Nous respectons et honorons vos traditions et pratiques culturelles',

      // Financial Literacy Additional Keys
      financialBasics: 'Bases Financières',
      savingsStrategies: 'Stratégies d\'Épargne',
      creditAndLoans: 'Crédit et Prêts',
      businessFinance: 'Finance d\'Entreprise',
      financialTip1Desc: 'Commencez par de petites épargnes régulières. Même épargner un petit montant régulièrement construit de bonnes habitudes.',
      financialTip2Desc: 'Suivez vos revenus et dépenses pour comprendre vos habitudes de dépenses et identifier les domaines d\'épargne.',
      financialTip3Desc: 'Construisez un fonds d\'urgence pour couvrir les dépenses imprévues et éviter l\'emprunt à coût élevé.',
      emergencyFund: 'Fonds d\'Urgence',
      emergencyFundDesc: 'Épargnez 3-6 mois de dépenses pour des situations imprévues comme les urgences médicales ou la perte d\'emploi.',
      goalSetting: 'Fixation d\'Objectifs',
      goalSettingDesc: 'Fixez des objectifs financiers spécifiques et réalisables avec des échéances pour rester motivé et concentré.',
      automaticSavings: 'Épargne Automatique',
      automaticSavingsDesc: 'Configurez des transferts automatiques pour rendre l\'épargne sans effort et cohérente.',
      creditRights: 'Vos Droits en tant qu\'Emprunteur',
      creditRightsDesc: 'Comprenez vos droits lors de l\'emprunt d\'argent et comment vous protéger contre les pratiques déloyales.',
      loanTypes: 'Types de Prêts',
      loanTypesDesc: 'Apprenez sur les différents types de prêts, leurs coûts et quand chacun pourrait être approprié.',
      avoidingDebt: 'Éviter les Pièges de Dette',
      avoidingDebtDesc: 'Reconnaissez l\'emprunt à coût élevé et les pratiques de prêt prédateur qui peuvent mener à des cycles de dette.',
      businessBudget: 'Budgétisation d\'Entreprise',
      businessBudgetDesc: 'Créez et maintenez un budget pour votre entreprise créative pour suivre les revenus et dépenses.',
      pricingStrategy: 'Prix de Votre Travail',
      pricingStrategyDesc: 'Apprenez comment fixer le prix de votre travail créatif équitablement tout en couvrant les coûts et en réalisant un profit.',
      cashFlow: 'Gestion du Flux de Trésorerie',
      cashFlowDesc: 'Comprenez le timing des revenus et dépenses pour maintenir des finances d\'entreprise saines.',
      groupSpecificTips: 'Conseils pour Groupes Spécifiques',
      groupSpecificTipsDesc: 'Conseils financiers adaptés à différentes communautés et circonstances.',
      refugeeFinancialTips: 'Conseils Financiers pour Réfugiés',
      refugeeTip1: 'Commencez à construire un historique de crédit avec de petits prêts ou cartes de crédit gérables',
      refugeeTip2: 'Connectez-vous avec des organisations communautaires qui fournissent l\'éducation financière et le soutien',
      refugeeTip3: 'Apprenez sur les options bancaires et services disponibles dans votre nouvelle localisation',
      pwdFinancialTips: 'Conseils Financiers pour Personnes Handicapées',
      pwdTip1: 'Recherchez les prestations d\'invalidité et programmes d\'assistance financière disponibles',
      pwdTip2: 'Considérez les options bancaires adaptées aux handicaps et services financiers accessibles',
      pwdTip3: 'Construisez un réseau de soutien pour la prise de décision et planification financière',
      lgbtqiFinancialTips: 'Conseils Financiers pour Communauté LGBTQI+',
      lgbtqiTip1: 'Comprenez vos droits dans les services financiers et cherchez des fournisseurs inclusifs',
      lgbtqiTip2: 'Considérez les protections légales pour la planification financière et successorale',
      lgbtqiTip3: 'Connectez-vous avec des conseillers financiers LGBTQI+-friendly et ressources communautaires',
      creativeFinancialTips: 'Conseils Financiers pour Professionnels Créatifs',
      creativeTip1: 'Diversifiez les sources de revenus pour réduire la vulnérabilité financière',
      creativeTip2: 'Mettez de côté de l\'argent pour les taxes et périodes de revenus irréguliers',
      creativeTip3: 'Investissez dans vos compétences et équipement pour augmenter le potentiel de gains',
    },
    ar: {
      welcome: 'مرحبًا بك في HEVA Inclusion',
      welcomeToHEVA: 'مرحبًا بك في HEVA Inclusion',
      inclusivePlatform: 'منصة شاملة لتمكين المجتمعات الإبداعية في جميع أنحاء إفريقيا',
      empoweringCreatives: 'تمكين المجتمعات الإبداعية',
      selectUserType: 'اختر نوع المستخدم',
      iAmCreative: 'أنا مبدع',
      iAmFieldAgent: 'أنا وكيل ميداني',
      hevaTeam: 'فريق HEVA',
      selectLanguage: 'اختر اللغة',
      helpInstructions: 'مساعدة / تعليمات',
      help: 'مساعدة',
      back: 'رجوع',
      close: 'إغلاق',
      understand: 'فهمت',
      creativeDescription: 'الفنانون والموسيقيون والمصممون والمحترفون المبدعون الباحثون عن الدعم والفرص',
      agentDescription: 'ضباط المنظمات غير الحكومية والوكلاء الميدانيون الذين يديرون البرامج الإبداعية',
      hevaDescription: 'أعضاء فريق HEVA والمسؤولون عن إدارة المنصة',
      additionalOptions: 'خيارات إضافية',
      securityInfo: 'معلومات الأمان',
      privacyPolicy: 'سياسة الخصوصية',
      accessibilityFeatures: 'ميزات الوصول',
      mobileOptimized: 'محسّن للجوال',
      desktopCompatible: 'متوافق مع سطح المكتب',
      ussdSupport: 'دعم USSD',
      voiceAssistance: 'مساعد صوتي',
      accessible: 'متاح',
      multilingual: 'متعدد اللغات',
      offlineMode: 'وضع عدم الاتصال',
      secure: 'آمن',
      adminPanel: 'لوحة الإدارة',
      analytics: 'تحليلات',
      securePlatform: 'منصة آمنة - بياناتك محمية',
      secureSession: 'جلسة آمنة',
      insecureSession: 'جلسة غير آمنة',
      minutesLeft: 'دقائق متبقية',
      emergencyExit: 'خروج الطوارئ',
      sessionExpired: 'انتهت الجلسة لأسباب أمنية',
      privacyAccepted: 'تم قبول سياسة الخصوصية',
      privacyRequired: 'مطلوب قبول سياسة الخصوصية',
      accessibility: 'إمكانية الوصول',
      accessibilityMode: 'وضع إمكانية الوصول',
      highContrast: 'تباين عالي',
      reducedMotion: 'حركة منخفضة',
      voiceAssistant: 'مساعد صوتي',
      audio: 'صوت',
      audioInstructions: 'تعليمات صوتية',
      smallFont: 'خط صغير',
      mediumFont: 'خط متوسط',
      largeFont: 'خط كبير',
      fontSizeChanged: 'تم تغيير حجم الخط',
      enabled: ' مفعل',
      disabled: ' معطل',
      audioNotSupported: 'الصوت غير مدعوم في هذا المتصفح',
      privacyNotice: 'إشعار الخصوصية والأمان',
      dataProtection: 'حماية البيانات',
      dataCollection: 'نقوم بجمع المعلومات الضرورية فقط لتقديم الخدمات',
      dataUsage: 'يتم استخدام بياناتك فقط لوظائف المنصة',
      dataSecurity: 'يتم تشفير جميع البيانات وتخزينها بأمان',
      dataRights: 'لديك سيطرة كاملة على معلوماتك الشخصية',
      safetyFeatures: 'ميزات الأمان',
      autoLogout: 'تسجيل الخروج التلقائي بعد عدم النشاط',
      dataEncryption: 'تشفير البيانات من طرف إلى طرف',
      acceptAndContinue: 'قبول ومتابعة',
      decline: 'رفض',
      securityFeatures: 'ميزات الأمان',
      dataEncryptionDesc: 'يتم تشفير جميع بياناتك باستخدام بروتوكولات قياسية',
      secureAuthentication: 'مصادقة آمنة',
      secureAuthenticationDesc: 'مصادقة متعددة العوامل وعمليات تسجيل دخول آمنة',
      autoLogoutDesc: 'تسجيل الخروج التلقائي بعد 30 دقيقة من عدم النشاط لأمانك',
      emergencyExitDesc: 'زر خروج سريع لمسح جميع البيانات وإعادة التوجيه إلى صفحة آمنة',
      keyboardShortcuts: 'اختصارات لوحة المفاتيح',
      alt1Creative: 'Alt + 1: اختر مبدع',
      alt2Agent: 'Alt + 2: اختر وكيل ميداني',
      alt3HEVA: 'Alt + 3: اختر فريق HEVA',
      altHHelp: 'Alt + H: مساعدة',
      altLLanguage: 'Alt + L: لغة',
      escapeExit: 'Escape: خروج الطوارئ',

      // Enhanced Onboarding - Marginalized Groups
      onboardingStep1Title: 'المعلومات الأساسية',
      onboardingStep1Desc: 'أخبرنا عن نفسك',
      onboardingStep2Title: 'الهوية والمجتمع',
      onboardingStep2Desc: 'ساعدنا في فهم خلفيتك واحتياجاتك',
      onboardingStep3Title: 'الوصول والتكنولوجيا',
      onboardingStep3Desc: 'أخبرنا عن جهازك واحتياجات الوصول',
      onboardingStep4Title: 'الثقة والمراجع',
      onboardingStep4Desc: 'بناء الثقة من خلال الروابط المجتمعية',
      onboardingStep5Title: 'الملف الشخصي الإبداعي',
      onboardingStep5Desc: 'شارك عملك الإبداعي وخبرتك',
      onboardingStep6Title: 'المقدمة الصوتية',
      onboardingStep6Desc: 'سجل مقدمة صوتية موجزة (اختياري)',
      onboardingStep7Title: 'المراجعة والموافقة',
      onboardingStep7Desc: 'راجع معلوماتك وقدم موافقتك',

      // Inclusive Identity Fields
      labelGender: 'الهوية الجنسية',
      selectGender: 'اختر جنسك',
      genderMale: 'ذكر',
      genderFemale: 'أنثى',
      genderNonBinary: 'غير ثنائي',
      genderOther: 'آخر',
      genderPreferNotToSay: 'أفضل عدم القول',
      specifyGender: 'يرجى تحديد جنسك',
      
      labelDisability: 'هل لديك إعاقة؟',
      selectDisability: 'اختر حالة الإعاقة',
      disabilityYes: 'نعم',
      disabilityNo: 'لا',
      disabilityPreferNotToSay: 'أفضل عدم القول',
      selectDisabilityType: 'اختر نوع الإعاقة',
      disabilityVisual: 'إعاقة بصرية',
      disabilityHearing: 'إعاقة سمعية',
      disabilityMobility: 'إعاقة حركية',
      disabilityCognitive: 'إعاقة معرفية',
      disabilitySpeech: 'إعاقة في النطق',
      disabilityOther: 'آخر',
      specifyDisability: 'يرجى تحديد إعاقتك',

      // Marginalized Groups
      labelMarginalizedGroups: 'أي من هذه يصفك؟',
      marginalizedGroupsHelp: 'اختر كل ما ينطبق. هذا يساعدنا في تقديم دعم أفضل.',
      groupRefugee: 'لاجئ',
      groupPWD: 'شخص ذو إعاقة',
      groupLGBTQI: 'LGBTQI+',
      groupCreative: 'محترف إبداعي',
      groupLowIncome: 'دخل منخفض',
      groupLowLiteracy: 'مستوى تعليمي منخفض',
      groupRural: 'مجتمع ريفي',
      groupYouth: 'شباب (18-25)',
      groupElderly: 'مسن (65+)',
      groupOther: 'آخر',
      specifyOtherGroup: 'يرجى تحديد',
      noneSelected: 'لم يتم اختيار أي شيء',

      // Device Access & Technology
      labelPrimaryDevice: 'ما الجهاز الذي تستخدمه أكثر؟',
      deviceSmartphone: 'هاتف ذكي',
      deviceFeaturePhone: 'هاتف عادي (هاتف بسيط)',
      deviceShared: 'جهاز مشترك',
      deviceComputer: 'كمبيوتر/لابتوب',
      deviceNone: 'لا يوجد جهاز',
      
      labelInternetAccess: 'كم مرة لديك إمكانية الوصول للإنترنت؟',
      selectInternetAccess: 'اختر إمكانية الوصول للإنترنت',
      internetAlways: 'متاح دائماً',
      internetSometimes: 'متاح أحياناً',
      internetRarely: 'متاح نادراً',
      internetNever: 'غير متاح أبداً',
      
      labelLiteracyLevel: 'ما هو مستوى تعليمك؟',
      selectLiteracyLevel: 'اختر مستوى التعليم',
      literacyHigh: 'عالي (يمكن القراءة والكتابة جيداً)',
      literacyMedium: 'متوسط (قراءة وكتابة أساسية)',
      literacyLow: 'منخفض (قراءة وكتابة محدودة)',
      literacyNone: 'لا يمكن القراءة أو الكتابة',
      
      labelPreferredFormat: 'كيف تفضل استلام المعلومات؟',
      formatText: 'نص',
      formatAudio: 'صوت',
      formatVideo: 'فيديو',
      formatIcons: 'أيقونات وصور',

      // Trust & Social Proof
      trustBasedOnboarding: 'التسجيل القائم على الثقة',
      trustBasedOnboardingDesc: 'نؤمن ببناء الثقة من خلال الروابط المجتمعية. يمكنك تقديم مرجع من شخص يعرفك.',
      hasReference: 'لدي مرجع أو اتصال مجتمعي',
      labelReferenceName: 'اسم المرجع',
      placeholderReferenceName: 'أدخل اسم المرجع',
      labelReferencePhone: 'هاتف المرجع',
      placeholderReferencePhone: 'أدخل رقم هاتف المرجع',
      labelReferenceRelationship: 'العلاقة مع المرجع',
      selectReferenceRelationship: 'اختر العلاقة',
      referenceCommunityLeader: 'قائد مجتمعي',
      referencePeer: 'زميل/صديق',
      referenceMentor: 'مرشد',
      referenceFamily: 'عضو عائلة',
      referenceOther: 'آخر',
      
      privacyOptions: 'خيارات الخصوصية',
      enablePrivacyMode: 'تفعيل وضع الخصوصية',
      privacyModeHelp: 'وضع الخصوصية يخفي المعلومات الحساسة ويوفر أماناً إضافياً.',

      // Consent
      consentTitle: 'الموافقة وحماية البيانات',
      consentDataCollection: 'أوافق على جمع ومعالجة HEVA لبياناتي لخدمات الدعم',
      consentContact: 'أوافق على الاتصال بي بخصوص فرص الدعم',

      // Enhanced Creative Fields
      creativeFieldVisualArts: 'الفنون البصرية',
      creativeFieldMusic: 'الموسيقى',
      creativeFieldDance: 'الرقص',
      creativeFieldTheater: 'المسرح',
      creativeFieldFilmVideo: 'السينما والفيديو',
      creativeFieldPhotography: 'التصوير',
      creativeFieldCrafts: 'الحرف اليدوية',
      creativeFieldDigitalArts: 'الفنون الرقمية',
      creativeFieldLiterature: 'الأدب',
      creativeFieldFashionDesign: 'تصميم الأزياء',
      creativeFieldOther: 'آخر',

      // Experience Levels
      experienceBeginner: 'مبتدئ',
      experienceIntermediate: 'متوسط',
      experienceAdvanced: 'متقدم',
      experienceExpert: 'خبير',

      // Form Labels
      labelFullName: 'الاسم الكامل',
      labelEmail: 'عنوان البريد الإلكتروني',
      labelPhone: 'رقم الهاتف',
      labelLocation: 'الموقع',
      labelCreativeField: 'المجال الإبداعي',
      labelExperience: 'مستوى الخبرة',
      labelBio: 'السيرة الذاتية/الوصف',
      labelProfileImage: 'صورة الملف الشخصي',

      // Placeholders
      placeholderFullName: 'أدخل اسمك الكامل',
      placeholderEmail: 'أدخل عنوان بريدك الإلكتروني',
      placeholderPhone: 'أدخل رقم هاتفك',
      placeholderLocation: 'أدخل موقعك',
      placeholderCreativeField: 'اختر مجالك الإبداعي',
      placeholderExperience: 'اختر مستوى خبرتك',
      placeholderBio: 'أخبرنا عن نفسك وعملك الإبداعي',

      // Voice Recording
      startRecording: 'ابدأ التسجيل',
      reRecord: 'إعادة التسجيل',
      voiceRecorded: 'تم تسجيل المقدمة الصوتية',
      voiceRecordedSuccess: 'تم تسجيل المقدمة الصوتية بنجاح!',
      recordingHelp: 'سجل مقدمة موجزة عن نفسك وعملك الإبداعي',
      microphoneAccessError: 'لا يمكن الوصول للميكروفون',

      // File Upload
      chooseImage: 'اختر صورة',
      uploaded: 'تم الرفع',
      notUploaded: 'لم يتم الرفع',
      recorded: 'تم التسجيل',
      notRecorded: 'لم يتم التسجيل',

      // Status
      status: 'الحالة',
      notProvided: 'غير مقدم',
      notSpecified: 'غير محدد',

      // Navigation
      previous: 'السابق',
      next: 'التالي',
      completeProfile: 'إكمال الملف الشخصي',
      profileCreatedSuccess: 'تم إنشاء الملف الشخصي بنجاح!',
      profileCreationFailed: 'فشل في إنشاء الملف الشخصي',
      profileCreationError: 'حدث خطأ',

      // Financial Literacy Content
      financialLiteracyTitle: 'التثقيف المالي',
      financialLiteracyDesc: 'تعلم إدارة المال وبناء الأمان المالي',
      financialTip1: 'وفر مبلغاً صغيراً بانتظام، حتى لو كان قليلاً',
      financialTip2: 'تتبع دخلك ومصروفاتك',
      financialTip3: 'ابنِ مدخرات طارئة للتكاليف غير المتوقعة',
      financialTip4: 'تعلم طرق مختلفة للادخار والاستثمار',
      financialTip5: 'افهم حقوقك كمقترض',
      
      // Anti-Fraud & Transparency
      transparencyTitle: 'الشفافية والثقة',
      transparencyDesc: 'نحن ملتزمون بالشفافية ومنع الاحتيال',
      fraudPrevention: 'منع الاحتيال',
      fraudPreventionDesc: 'لدينا أنظمة لمنع الاحتيال وضمان وصول الأموال للأشخاص الصحيحين',
      reportingFraud: 'الإبلاغ عن الاحتيال',
      reportingFraudDesc: 'إذا كنت تشك في احتيال، يرجى الإبلاغ عنه فوراً',
      fundTracking: 'تتبع الأموال',
      fundTrackingDesc: 'جميع الأموال يتم تتبعها ومراقبتها لضمان الاستخدام المناسب',

      // Cultural Adaptation
      culturalAdaptationTitle: 'التكيف الثقافي',
      culturalAdaptationDesc: 'منصتنا تتكيف مع سياقك الثقافي واحتياجاتك',
      localExamples: 'أمثلة محلية',
      localExamplesDesc: 'نستخدم أمثلة ومحتوى ذا صلة بمجتمعك',
      culturalSensitivity: 'الحساسية الثقافية',
      culturalSensitivityDesc: 'نحترم ونكرم تقاليدك وممارساتك الثقافية',

      // Financial Literacy Additional Keys
      financialBasics: 'أساسيات المالية',
      savingsStrategies: 'استراتيجيات الادخار',
      creditAndLoans: 'الائتمان والقروض',
      businessFinance: 'تمويل الأعمال',
      financialTip1Desc: 'ابدأ بالادخار الصغير المنتظم. حتى الادخار بمبلغ صغير بانتظام يبني عادات جيدة.',
      financialTip2Desc: 'تتبع دخلك ومصروفاتك لفهم أنماط إنفاقك وتحديد مجالات الادخار.',
      financialTip3Desc: 'ابنِ صندوق طوارئ لتغطية المصروفات غير المتوقعة وتجنب الاقتراض عالي التكلفة.',
      emergencyFund: 'صندوق الطوارئ',
      emergencyFundDesc: 'وفر 3-6 أشهر من المصروفات للحالات غير المتوقعة مثل الطوارئ الطبية أو فقدان العمل.',
      goalSetting: 'تحديد الأهداف',
      goalSettingDesc: 'حدد أهدافاً مالية محددة وقابلة للتحقيق مع جداول زمنية للبقاء متحمساً ومركزاً.',
      automaticSavings: 'الادخار التلقائي',
      automaticSavingsDesc: 'قم بإعداد التحويلات التلقائية لجعل الادخار سهلاً ومتسقاً.',
      creditRights: 'حقوقك كمقترض',
      creditRightsDesc: 'افهم حقوقك عند اقتراض المال وكيفية حماية نفسك من الممارسات غير العادلة.',
      loanTypes: 'أنواع القروض',
      loanTypesDesc: 'تعلم عن أنواع القروض المختلفة وتكاليفها ومتى قد يكون كل منها مناسباً.',
      avoidingDebt: 'تجنب فخ الديون',
      avoidingDebtDesc: 'تعرف على الاقتراض عالي التكلفة وممارسات الإقراض المفترسة التي يمكن أن تؤدي إلى دورات الديون.',
      businessBudget: 'ميزانية الأعمال',
      businessBudgetDesc: 'أنشئ وحافظ على ميزانية لعملك الإبداعي لتتبع الدخل والمصروفات.',
      pricingStrategy: 'تسعير عملك',
      pricingStrategyDesc: 'تعلم كيفية تسعير عملك الإبداعي بإنصاف مع تغطية التكاليف وتحقيق الربح.',
      cashFlow: 'إدارة التدفق النقدي',
      cashFlowDesc: 'افهم توقيت الدخل والمصروفات للحفاظ على صحة المالية التجارية.',
      groupSpecificTips: 'نصائح لمجموعات محددة',
      groupSpecificTipsDesc: 'نصائح مالية مخصصة لمجتمعات وظروف مختلفة.',
      refugeeFinancialTips: 'نصائح مالية للاجئين',
      refugeeTip1: 'ابدأ ببناء تاريخ ائتماني مع قروض صغيرة أو بطاقات ائتمان قابلة للإدارة',
      refugeeTip2: 'تواصل مع المنظمات المجتمعية التي توفر التعليم المالي والدعم',
      refugeeTip3: 'تعلم عن خيارات البنوك والخدمات المتاحة في موقعك الجديد',
      pwdFinancialTips: 'نصائح مالية للأشخاص ذوي الإعاقة',
      pwdTip1: 'ابحث عن مزايا الإعاقة وبرامج المساعدة المالية المتاحة لك',
      pwdTip2: 'فكر في خيارات البنوك الصديقة للإعاقة والخدمات المالية المتاحة',
      pwdTip3: 'ابنِ شبكة دعم لاتخاذ القرارات المالية والتخطيط',
      lgbtqiFinancialTips: 'نصائح مالية لمجتمع LGBTQI+',
      lgbtqiTip1: 'افهم حقوقك في الخدمات المالية وابحث عن مقدمي الخدمات الشاملين',
      lgbtqiTip2: 'فكر في الحماية القانونية للتخطيط المالي والتخطيط العقاري',
      lgbtqiTip3: 'تواصل مع المستشارين الماليين الصديقين لـ LGBTQI+ والموارد المجتمعية',
      creativeFinancialTips: 'نصائح مالية للمحترفين الإبداعيين',
      creativeTip1: 'نوع مصادر الدخل لتقليل الضعف المالي',
      creativeTip2: 'وفر مالاً للضرائب وفترات الدخل غير المنتظم',
      creativeTip3: 'استثمر في مهاراتك ومعداتك لزيادة إمكانات الكسب',
    }
  };

  const t = (key) => {
    return translations[currentLanguage][key] || translations.en[key] || key;
  };

  const setLanguage = (language) => {
    setCurrentLanguage(language);
    localStorage.setItem('preferredLanguage', language);
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}; 